### PR TITLE
feat(file-picker): add `skipTranscoding` option on iOS

### PR DESCRIPTION
**Pull request by thomasjohansen**
This avoids transcoding. Ie giving the original file like .heic and not .jpeg.

Documentation of the configuration can be found here:
https://developer.apple.com/documentation/photokit/phpickerconfiguration/assetrepresentationmode/current

### CODE REVIEW

**Comment by robingenz** [comment]
Great idea. However, this enhancement will either have to be an opt-in or wait until the next major release, as this is a breaking change.

**Comment by thomasjohansen** [comment]
@robingenz I've added a flag to handle this now. Would that be a way of solving it?

**Comment by robingenz** [comment]
Yes 👍

**Comment by robingenz** [comment]
@thomasjohansen Please add a `minor` changeset using `npm run changeset` with the following message: 

```
feat(ios): add `skipTranscoding` option
```

**Comment by robingenz** [comment]
@thomasjohansen Please undo your last changes and do what I described in [this comment](https://github.com/capawesome-team/capacitor-plugins/pull/42#issuecomment-1609561111). You need to run `npm run changeset` to generate a changeset file. The version is increased by the CI.

**Review by robingenz — APPROVED** [review]

**Comment by robingenz** [comment]
@thomasjohansen Thank you!

**Pull request merged**
