### PR TITLE
fix(file-picker): no files were returned on Android 10 and below with the Samsung Gallery app

### LINKED ISSUE #292: bug: FilePicker.pickImages does not return any images on Android 9 or Android 10 when Samsung Gallery is used
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Bluetooth Low Energy
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Compressor
- [ ] File Opener
- [X] File Picker
- [ ] Live Update
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [ ] Printer
- [ ] Screen Orientation
- [ ] Zip

### Version

6.0.1

### Platform(s)

- [X] Android
- [ ] iOS
- [ ] Web

### Current behavior

Selecting images using the dialog that appears does not return any images (i.e. an empty array is returned), when testing on a Samsung Galaxy S8 running Android 9, this issue seems similar to #40 that was reported by @garrensweet which as far as I can tell didn't have any resolution.

The following is returning 0 images as per screenshots below.

```
 const results = await FilePicker.pickImages();

 alert(`Selected ${results.files.length} images`);

```

### Expected behavior

The correct number of images should be returned when selecting them.

### Reproduction

https://github.com/webfletch/Capawesome.Filepicker.Issue

### Steps to reproduce

Run the project on a physical device running Android 9.
Press the "Select images" button.
Select at least 1 image.
Alert will show that no images have been selected.

### Capacitor doctor

Capacitor Doctor   

Latest Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2

[success] Android looking great! 👌

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

### PR DESCRIPTION
**Pull request by webfletch**
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] The changes have been tested successfully.
- [ ] A changeset has been created (`npm run changeset`).
- [ ] I have read and followed the [pull request guidelines](https://capawesome.io/contributing/pull-requests/).

---

Close #292

### CODE REVIEW

**Review by robingenz — CHANGES_REQUESTED** [review]
Please run `npm run changeset` to add a changeset file.

**Review by robingenz — APPROVED** [review]
Thank you! Did you test the changes?

**Comment by webfletch** [comment]
> Thank you! Did you test the changes?

I did and it seemed to be working fine but I have just done some further checks using BrowserStack on some more devices and found that it fails on Android 9 and Android 8 when using the Samsung Gallery App with the following error, however on Android 9 on a physical device it works okay:

> E/FilePickerPlugin(24072): Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media/11 from pid=24072, uid=10460 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()

These are the platforms I have tested on:

### **BrowserStack devices**

**Samsung Gallery App**
Galaxy S24 (Android 14)
Galaxy S23 (Android 13)
Galaxy S22 (Android 12)
Galaxy S21 (Android 11)
Galaxy S20 (Android 10)
Galaxy S10 (Android 9) - **FAILED**
Galaxy S9 (Android 8) - **FAILED**

**Google Photos App**
Pixel 9 (Android 14)
Pixel 4 (Android 10)
Galaxy S10 (Android 9)
Pixel 3a (Android 9)

### Physical device

**Samsung Gallery App**
Galaxy S8 (Android 9)

**Google Photos App**
Galaxy S8 (Android 9)

I will need to investigate further to see why it is failing on those Browserstack devices.

**Comment by robingenz** [comment]
The current implementation failed on these devices too, right?

**Comment by webfletch** [comment]
> The current implementation failed on these devices too, right?

The current implementation failed on Android 9 and Android 10 (I never tested the current implementation on Android 8).

The changes I have made fail on Android 9 and Android 8 (although for some reason it actually works okay on a physical device I have running Android 9 which is what I did the original testing on but it fails on Android 9 on a BrowserStack device).

This is a different error/issue than the original implementation, it is related to the permissions for "READ_EXTERNAL_STORAGE", whereby it seems that Android 9 and Android 8 (and possibly lower versions) need to request from the user this permission if they are using the "Samsung Gallery App".

I am working on refactoring the code so that it will run a check for the "READ_EXTERNAL_STORAGE" permission. Something along the lines of the following which will need to be checked in each methods (ie. "pickImages()", "pickMedia()" etc).

```
if (ContextCompat.checkSelfPermission(this, android.Manifest.permission.READ_EXTERNAL_STORAGE) 
    != PackageManager.PERMISSION_GRANTED) 
{
    ActivityCompat.requestPermissions(this, new String[]{android.Manifest.permission.READ_EXTERNAL_STORAGE}, 
        REQUEST_CODE);  
}
```

**Comment by robingenz** [comment]
I would like to move the permission request to a separate pull request. In the end, this error message is also an improvement. Previously, no files were simply returned by the plugin. Now, as a developer, you at least get an error message and can indicate to the user that something has gone wrong.

**Comment by webfletch** [comment]
@robingenz Okay I am fairly new to PR's and modifying open source code etc, so does this mean that this PR is fine and will be pushed live and then you would like me to create another PR that will deal with the showing permission message as needed for Android 8 and 9 users that have the Samsung Gallery App?

**Comment by robingenz** [comment]
Yes, this PR is fine. Sorry, I completely forgot to merge. I will have a look at the permissions myself. Could you create a new issue for the second permission error please? This makes tracking the issue easier.

**Comment by webfletch** [comment]
Created issue #297 as requested.

**Pull request merged**
